
'use client';

import { useState } from 'react';
import { ethers } from 'ethers';

const GCLOUD_RPC = 'https://blockchain.googleapis.com/v1/projects/aenzbi-cloud/locations/us-central1/endpoints/ethereum-mainnet/rpc?key=AIzaSyCTkj44NjTgfFELMP89ufrmHeWnW6utbG8';

const ERC20_ABI = [
  "function name() view returns (string)",
    "function symbol() view returns (string)",
      "function balanceOf(address) view returns (uint256)",
        "function decimals() view returns (uint8)",
        ];

        const TOKENS = [
          {
              name: "USDT",
                  address: "0xdAC17F958D2ee523a2206206994597C13D831ec7"
                    },
                      {
                          name: "USDC",
                              address: "0xA0b86991C6218b36c1d19D4a2e9Eb0cE3606eb48"
                                },
                                  {
                                      name: "DAI",
                                          address: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
                                            },
                                              {
                                                  name: "WETH",
                                                      address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
                                                        },
                                                        ];

                                                        export default function Home() {
                                                          const [address, setAddress] = useState('');
                                                            const [balance, setBalance] = useState('');
                                                              const [tokens, setTokens] = useState<any[]>([]);
                                                                const [txs, setTxs] = useState<any[]>([]);
                                                                  const [error, setError] = useState('');

                                                                    const fetchWalletData = async () => {
                                                                        setError('');
                                                                            setTokens([]);
                                                                                try {
                                                                                      const provider = new ethers.JsonRpcProvider(GCLOUD_RPC);
                                                                                            const bal = await provider.getBalance(address);
                                                                                                  setBalance(ethers.formatEther(bal));

                                                                                                        const history = await provider.getHistory(address);
                                                                                                              setTxs(history.slice(-10).reverse());

                                                                                                                    const tokenBalances = await Promise.all(
                                                                                                                            TOKENS.map(async token => {
                                                                                                                                      try {
                                                                                                                                                  const contract = new ethers.Contract(token.address, ERC20_ABI, provider);
                                                                                                                                                              const [symbol, rawBalance, decimals] = await Promise.all([
                                                                                                                                                                            contract.symbol(),
                                                                                                                                                                                          contract.balanceOf(address),
                                                                                                                                                                                                        contract.decimals()
                                                                                                                                                                                                                    ]);
                                                                                                                                                                                                                                return {
                                                                                                                                                                                                                                              symbol,
                                                                                                                                                                                                                                                            balance: ethers.formatUnits(rawBalance, decimals)
                                                                                                                                                                                                                                                                        };
                                                                                                                                                                                                                                                                                  } catch {
                                                                                                                                                                                                                                                                                              return null;
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                })
                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                            setTokens(tokenBalances.filter(Boolean));
                                                                                                                                                                                                                                                                                                                                } catch (err: any) {
                                                                                                                                                                                                                                                                                                                                      setError(err.message);
                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                            };

                                                                                                                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                                                                                                                  <main className="p-6 max-w-3xl mx-auto">
                                                                                                                                                                                                                                                                                                                                                        <h1 className="text-2xl font-bold mb-4">GCloud Ethereum Explorer + ERC-20</h1>

                                                                                                                                                                                                                                                                                                                                                              <input
                                                                                                                                                                                                                                                                                                                                                                      type="text"
                                                                                                                                                                                                                                                                                                                                                                              className="w-full p-2 border mb-2"
                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Enter wallet address"
                                                                                                                                                                                                                                                                                                                                                                                              value={address}
                                                                                                                                                                                                                                                                                                                                                                                                      onChange={e => setAddress(e.target.value)}
                                                                                                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                                                                                                  <button className="bg-blue-600 text-white px-4 py-2 rounded" onClick={fetchWalletData}>
                                                                                                                                                                                                                                                                                                                                                                                                                          Track Wallet
                                                                                                                                                                                                                                                                                                                                                                                                                                </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                      {error && <p className="text-red-600 mt-2">{error}</p>}

                                                                                                                                                                                                                                                                                                                                                                                                                                            {balance && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p><strong>ETH Balance:</strong> {balance} ETH</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {tokens.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-lg font-semibold">ERC-20 Token Balances</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <ul className="space-y-2 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {tokens.map(token => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <li key={token.symbol} className="border p-2 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <strong>{token.symbol}</strong>: {token.balance}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {txs.length > 0 && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="mt-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h2 className="text-lg font-semibold">Recent Transactions</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <ul className="space-y-2 mt-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {txs.map(tx => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <li key={tx.hash} className="text-sm border p-2 rounded">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p><strong>Hash:</strong> <a href={`https://etherscan.io/tx/${tx.hash}`} target="_blank" className="text-blue-600 underline">{tx.hash.slice(0, 40)}...</a></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p><strong>From:</strong> {tx.from}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p><strong>To:</strong> {tx.to}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p><strong>Value:</strong> {ethers.formatEther(tx.value)} ETH</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </li>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }